/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/products": {
    /**
     * List products
     * @description Retrieve all of the existing products for the authenticated user.
     */
    get: operations["/products.get"];
  };
  "/products/{id}": {
    /**
     * Get a product
     * @description Retrieve the details of a product.
     */
    get: operations["/products/{id}.get"];
    /**
     * Delete a product
     * @description Permanently delete a product.
     */
    delete: operations["/products/{id}.delete"];
  };
  "/products/{id}/enable": {
    /**
     * Enable a product
     * @description Enable an existing product.
     */
    put: operations["/products/{id}/enable.put"];
  };
  "/products/{id}/disable": {
    /**
     * Disable a product
     * @description Disable an existing product.
     */
    put: operations["/products/{id}/disable.put"];
  };
  "/products/{product_id}/variant_categories": {
    /**
     * List variant categories
     * @description Retrieve all of the existing variant categories of a product.
     */
    get: operations["/products/{product_id}/variant_categories.get"];
    /**
     * Create a variant category
     * @description Create a new variant category on a product.
     */
    post: operations["/products/{product_id}/variant_categories.post"];
  };
  "/products/{product_id}/variant_categories/{id}": {
    /**
     * Get a variant category
     * @description Retrieve the details of a variant category of a product.
     */
    get: operations["/products/{product_id}/variant_categories/{id}.get"];
    /**
     * Update a variant category
     * @description Edit a variant category of an existing product.
     */
    put: operations["/products/{product_id}/variant_categories/{id}.put"];
    /**
     * Delete a variant category
     * @description Permanently delete a variant category of a product.
     */
    delete: operations["/products/{product_id}/variant_categories/{id}.delete"];
  };
  "/products/{product_id}/variant_categories/{variant_category_id}/variants": {
    /**
     * List variants
     * @description Retrieve all of the existing variants in a variant category.
     */
    get: operations["/products/{product_id}/variant_categories/{variant_category_id}/variants.get"];
    /**
     * Create a new variant
     * @description Create a new variant of a product.
     */
    post: operations["/products/{product_id}/variant_categories/{variant_category_id}/variants.post"];
  };
  "/products/{product_id}/variant_categories/{variant_category_id}/variants/{id}": {
    /**
     * Get a variant
     * @description Retrieve the details of a variant of a product.
     */
    get: operations["/products/{product_id}/variant_categories/{variant_category_id}/variants/{id}.get"];
    /**
     * Update a variant
     * @description Edit a variant of an existing product.
     */
    put: operations["/products/{product_id}/variant_categories/{variant_category_id}/variants/{id}.put"];
    /**
     * Delete a variant
     * @description Permanently delete a variant of a product.
     */
    delete: operations["/products/{product_id}/variant_categories/{variant_category_id}/variants/{id}.delete"];
  };
  "/products/{product_id}/offer_codes": {
    /**
     * List offer codes
     * @description Retrieve all of the existing offer codes for a product. Either amount_cents or percent_off will be returned depending if the offer code is a fixed amount off or a percentage off. A universal offer code is one that applies to all products.
     */
    get: operations["/products/{product_id}/offer_codes.get"];
    /**
     * Create an offer code
     * @description Create a new offer code for a product. Default offer code is in cents. A universal offer code is one that applies to all products.
     */
    post: operations["/products/{product_id}/offer_codes.post"];
  };
  "/products/{product_id}/offer_codes/{id}": {
    /**
     * Get an offer codes
     * @description Retrieve the details of a specific offer code of a product
     */
    get: operations["/products/{product_id}/offer_codes/{id}.get"];
    /**
     * Update an offer code
     * @description Edit an existing product's offer code.
     */
    put: operations["/products/{product_id}/offer_codes/{id}.put"];
    /**
     * Delete an offer code
     * @description Permanently delete a product's offer code.
     */
    delete: operations["/products/{product_id}/offer_codes/{id}.delete"];
  };
  "/products/{product_id}/custom_fields": {
    /**
     * List custom fields
     * @description Retrieve all of the existing custom fields for a product.
     */
    get: operations["/products/{product_id}/custom_fields.get"];
    /**
     * Create a custom field
     * @description Create a new custom field for a product.
     */
    post: operations["/products/{product_id}/custom_fields.post"];
  };
  "/products/{product_id}/custom_fields/{name}": {
    /**
     * Update a custom field
     * @description Edit an existing product's custom field.
     */
    put: operations["/products/{product_id}/custom_fields/{name}.put"];
    /**
     * Delete a custom field
     * @description Permanently delete a product's custom field.
     */
    delete: operations["/products/{product_id}/custom_fields/{name}.delete"];
  };
  "/user": {
    /**
     * Get current user data
     * @description Retrieve the user's data.
     */
    get: operations["/user.get"];
  };
  "/resource_subscriptions": {
    /**
     * List resource subscriptions
     * @description Show all active subscriptions of user for the input resource.
     */
    get: operations["/resource_subscriptions.get"];
    /**
     * Subscribe to a resource
     * @description Subscribe to a resource. Currently there are 5 supported resource names - "sale", "refund", "dispute", "dispute_won", and "cancellation". sale - When subscribed to this resource, you will be notified of the user's sales with an HTTP POST to your post_url. The format of the POST is described on the Gumroad Ping page.refund - When subscribed to this resource, you will be notified of refunds to the user's sales with an HTTP POST to your post_url. The format of the POST is same as described on the Gumroad Ping page.dispute - When subscribed to this resource, you will be notified of the disputes raised against user's sales with an HTTP POST to your post_url. The format of the POST is described on the Gumroad Ping page.dispute_won - When subscribed to this resource, you will be notified of the sale disputes won by the user with an HTTP POST to your post_url. The format of the POST is described on the Gumroad Ping page.cancellation - When subscribed to this resource, you will be notified of cancellations of the user's subscribers with an HTTP POST to your post_url.In each POST request, Gumroad sends these parameters:
     * subscription_id: id of the subscription
     * product_id: id of the product
     * product_name: name of the product
     * user_id: user id of the subscriber
     * user_email: email address of the subscriber
     * purchase_ids: array of charge ids belonging to this subscription
     * created_at: timestamp when subscription was created
     * charge_occurrence_count: number of charges made for this subscription
     * recurrence: subscription duration - monthly/quarterly/biannually/yearly
     * cancelled: true if subscription has been cancelled, otherwise false
     * cancelled_at: timestamp at which subscription was cancelled
     * cancelled_by_admin: true if subscription was been cancelled by admin, otherwise not present
     * cancelled_by_buyer: true if subscription was been cancelled by buyer, otherwise not present
     * cancelled_by_seller: true if subscription was been cancelled by seller, otherwise not present
     * cancelled_due_to_payment_failures: true if subscription was been cancelled automatically because of payment failure, otherwise not present
     */
    put: operations["/resource_subscriptions.put"];
  };
  "/resource_subscriptions/{resource_subscription_id}": {
    /**
     * Unsubscribe from resource
     * @description Unsubscribe from a resource.
     */
    delete: operations["/resource_subscriptions/{resource_subscription_id}.delete"];
  };
  "/sales": {
    /**
     * List sales
     * @description Retrieves all of the successful sales by the authenticated user.
     */
    get: operations["/sales.get"];
  };
  "/sales/{id}": {
    /**
     * Get a sale
     * @description Retrieves the details of a sale by this user.
     */
    get: operations["/sales/{id}.get"];
  };
  "/sales/{id}/mark_as_shipped": {
    /**
     * Mark sale as shipped
     * @description Marks a sale as shipped.
     */
    put: operations["/sales/{id}/mark_as_shipped.put"];
  };
  "/sales/{id}/refund": {
    /**
     * Refund a sale
     * @description Refunds a sale.
     */
    put: operations["/sales/{id}/refund.put"];
  };
  "/products/{product_id}/subscribers": {
    /**
     * List product subscribers
     * @description Retrieves all of the active subscribers for one of the authenticated user's products.
     */
    get: operations["/products/{product_id}/subscribers.get"];
  };
  "/subscribers/{id}": {
    /**
     * Get a product subscriber
     * @description Retrieves the details of a subscriber to this user's product.
     */
    get: operations["/subscribers/{id}.get"];
  };
  "/licenses/verify": {
    /**
     * Verify a license
     * @description Verify a license
     */
    post: operations["/licenses/verify.post"];
  };
  "/licenses/enable": {
    /**
     * Enable a license
     * @description Enable a license
     */
    put: operations["/licenses/enable.put"];
  };
  "/licenses/disable": {
    /**
     * Disable a license
     * @description Disable a license
     */
    put: operations["/licenses/disable.put"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: {
    Body?: {
      content: {
        "application/json": {
          variant_category: string;
          title: string;
        };
      };
    };
    Body2?: {
      content: {
        "application/json": {
          variant: string;
          name: string;
          price_difference_cents: number;
          max_purchase_count?: number;
        };
      };
    };
    Body3?: {
      content: {
        "application/json": {
          product_permalink: string;
          license_key: string;
        };
      };
    };
  };
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * List products
   * @description Retrieve all of the existing products for the authenticated user.
   */
  "/products.get": {
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            products: {
                custom_permalink?: unknown;
                custom_receipt?: unknown;
                custom_summary: string;
                custom_fields?: unknown[];
                customizable_price?: unknown;
                description: string;
                deleted: boolean;
                max_purchase_count?: unknown;
                name: string;
                preview_url?: unknown;
                require_shipping: boolean;
                subscription_duration?: unknown;
                published: boolean;
                url: string;
                id: string;
                price: number;
                currency: string;
                short_url: string;
                formatted_price: string;
                file_info?: Record<string, never>;
                shown_on_profile: boolean;
                sales_count: string;
                sales_usd_cents: string;
              }[];
          };
        };
      };
    };
  };
  /**
   * Get a product
   * @description Retrieve the details of a product.
   */
  "/products/{id}.get": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            product: {
              custom_permalink?: unknown;
              custom_receipt?: unknown;
              custom_summary: string;
              custom_fields: unknown[];
              customizable_price?: unknown;
              description: string;
              deleted: boolean;
              max_purchase_count?: unknown;
              name: string;
              preview_url?: unknown;
              require_shipping: boolean;
              subscription_duration?: unknown;
              published: boolean;
              url: string;
              id: string;
              price: number;
              currency: string;
              short_url: string;
              formatted_price: string;
              file_info: Record<string, never>;
              shown_on_profile: boolean;
              sales_count: string;
              sales_usd_cents: string;
            };
          };
        };
      };
    };
  };
  /**
   * Delete a product
   * @description Permanently delete a product.
   */
  "/products/{id}.delete": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            message: string;
          };
        };
      };
    };
  };
  /**
   * Enable a product
   * @description Enable an existing product.
   */
  "/products/{id}/enable.put": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            product: {
              custom_permalink?: unknown;
              custom_receipt?: unknown;
              custom_summary: string;
              custom_fields: unknown[];
              customizable_price?: unknown;
              description: string;
              deleted: boolean;
              max_purchase_count?: unknown;
              name: string;
              preview_url?: unknown;
              require_shipping: boolean;
              subscription_duration?: unknown;
              published: boolean;
              url: string;
              id: string;
              price: number;
              currency: string;
              short_url: string;
              formatted_price: string;
              file_info: Record<string, never>;
              shown_on_profile: boolean;
              sales_count: string;
              sales_usd_cents: string;
            };
          };
        };
      };
    };
  };
  /**
   * Disable a product
   * @description Disable an existing product.
   */
  "/products/{id}/disable.put": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            product: {
              custom_permalink?: unknown;
              custom_receipt?: unknown;
              custom_summary: string;
              custom_fields: unknown[];
              customizable_price?: unknown;
              description: string;
              deleted: boolean;
              max_purchase_count?: unknown;
              name: string;
              preview_url?: unknown;
              require_shipping: boolean;
              subscription_duration?: unknown;
              published: boolean;
              url: string;
              id: string;
              price: number;
              currency: string;
              short_url: string;
              formatted_price: string;
              file_info: Record<string, never>;
              shown_on_profile: boolean;
              view_count: string;
              sales_count: string;
              sales_usd_cents: string;
            };
          };
        };
      };
    };
  };
  /**
   * List variant categories
   * @description Retrieve all of the existing variant categories of a product.
   */
  "/products/{product_id}/variant_categories.get": {
    parameters: {
      path: {
        product_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            variant_categories: {
                id: string;
                title: string;
              }[];
          };
        };
      };
    };
  };
  /**
   * Create a variant category
   * @description Create a new variant category on a product.
   */
  "/products/{product_id}/variant_categories.post": {
    parameters: {
      path: {
        product_id: string;
      };
    };
    requestBody: components["requestBodies"]["Body"];
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            variant_category: {
              id: string;
              title: string;
            };
          };
        };
      };
    };
  };
  /**
   * Get a variant category
   * @description Retrieve the details of a variant category of a product.
   */
  "/products/{product_id}/variant_categories/{id}.get": {
    parameters: {
      path: {
        product_id: string;
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            variant_category: {
              id: string;
              title: string;
            };
          };
        };
      };
    };
  };
  /**
   * Update a variant category
   * @description Edit a variant category of an existing product.
   */
  "/products/{product_id}/variant_categories/{id}.put": {
    parameters: {
      path: {
        product_id: string;
        id: string;
      };
    };
    requestBody: components["requestBodies"]["Body"];
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            variant_category: {
              id: string;
              title: string;
            };
          };
        };
      };
    };
  };
  /**
   * Delete a variant category
   * @description Permanently delete a variant category of a product.
   */
  "/products/{product_id}/variant_categories/{id}.delete": {
    parameters: {
      path: {
        product_id: string;
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            message: string;
          };
        };
      };
    };
  };
  /**
   * List variants
   * @description Retrieve all of the existing variants in a variant category.
   */
  "/products/{product_id}/variant_categories/{variant_category_id}/variants.get": {
    parameters: {
      path: {
        product_id: string;
        variant_category_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            variants: {
                id: string;
                max_purchase_count?: unknown;
                name: string;
                price_difference_cents: number;
              }[];
          };
        };
      };
    };
  };
  /**
   * Create a new variant
   * @description Create a new variant of a product.
   */
  "/products/{product_id}/variant_categories/{variant_category_id}/variants.post": {
    parameters: {
      path: {
        product_id: string;
        variant_category_id: string;
      };
    };
    requestBody: components["requestBodies"]["Body2"];
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            variant: {
              id: string;
              max_purchase_count?: unknown;
              name: string;
              price_difference_cents: number;
            };
          };
        };
      };
    };
  };
  /**
   * Get a variant
   * @description Retrieve the details of a variant of a product.
   */
  "/products/{product_id}/variant_categories/{variant_category_id}/variants/{id}.get": {
    parameters: {
      path: {
        product_id: string;
        variant_category_id: string;
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            variant: {
              id: string;
              max_purchase_count?: unknown;
              name: string;
              price_difference_cents: number;
            };
          };
        };
      };
    };
  };
  /**
   * Update a variant
   * @description Edit a variant of an existing product.
   */
  "/products/{product_id}/variant_categories/{variant_category_id}/variants/{id}.put": {
    parameters: {
      path: {
        product_id: string;
        variant_category_id: string;
        id: string;
      };
    };
    requestBody: components["requestBodies"]["Body2"];
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            variant: {
              id: string;
              max_purchase_count?: unknown;
              name: string;
              price_difference_cents: number;
            };
          };
        };
      };
    };
  };
  /**
   * Delete a variant
   * @description Permanently delete a variant of a product.
   */
  "/products/{product_id}/variant_categories/{variant_category_id}/variants/{id}.delete": {
    parameters: {
      path: {
        product_id: string;
        variant_category_id: string;
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            message: string;
          };
        };
      };
    };
  };
  /**
   * List offer codes
   * @description Retrieve all of the existing offer codes for a product. Either amount_cents or percent_off will be returned depending if the offer code is a fixed amount off or a percentage off. A universal offer code is one that applies to all products.
   */
  "/products/{product_id}/offer_codes.get": {
    parameters: {
      path: {
        product_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            offer_codes: {
                id: string;
                name: string;
                amount_cents: number;
                max_purchase_count?: unknown;
                universal: boolean;
                times_used: number;
              }[];
          };
        };
      };
    };
  };
  /**
   * Create an offer code
   * @description Create a new offer code for a product. Default offer code is in cents. A universal offer code is one that applies to all products.
   */
  "/products/{product_id}/offer_codes.post": {
    parameters: {
      path: {
        product_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          name: string;
          amount_off: number;
          /** @default cents */
          offer_type?: string;
          max_purchase_count?: number;
          /** @default false */
          universal: boolean;
        };
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            offer_code: {
              id: string;
              name: string;
              amount_cents: number;
              max_purchase_count?: unknown;
              times_used: number;
            };
          };
        };
      };
    };
  };
  /**
   * Get an offer codes
   * @description Retrieve the details of a specific offer code of a product
   */
  "/products/{product_id}/offer_codes/{id}.get": {
    parameters: {
      path: {
        product_id: string;
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            offer_code: {
              id: string;
              name: string;
              amount_cents: number;
              max_purchase_count?: unknown;
              times_used: number;
            };
          };
        };
      };
    };
  };
  /**
   * Update an offer code
   * @description Edit an existing product's offer code.
   */
  "/products/{product_id}/offer_codes/{id}.put": {
    parameters: {
      path: {
        product_id: string;
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          offer_code: string;
          max_purchase_count: number;
        };
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            offer_code: {
              id: string;
              name: string;
              amount_cents: number;
              max_purchase_count: number;
              universal: boolean;
            };
          };
        };
      };
    };
  };
  /**
   * Delete an offer code
   * @description Permanently delete a product's offer code.
   */
  "/products/{product_id}/offer_codes/{id}.delete": {
    parameters: {
      path: {
        product_id: string;
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            message: string;
          };
        };
      };
    };
  };
  /**
   * List custom fields
   * @description Retrieve all of the existing custom fields for a product.
   */
  "/products/{product_id}/custom_fields.get": {
    parameters: {
      path: {
        product_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            custom_fields: {
                name: string;
                required: string;
              }[];
          };
        };
      };
    };
  };
  /**
   * Create a custom field
   * @description Create a new custom field for a product.
   */
  "/products/{product_id}/custom_fields.post": {
    parameters: {
      path: {
        product_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          variant: string;
          name: string;
          required: boolean;
        };
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            custom_field: {
              name: string;
              required: string;
            };
          };
        };
      };
    };
  };
  /**
   * Update a custom field
   * @description Edit an existing product's custom field.
   */
  "/products/{product_id}/custom_fields/{name}.put": {
    parameters: {
      path: {
        product_id: string;
        name: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          variant: string;
          required: boolean;
        };
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            custom_field: {
              name: string;
              required: string;
            };
          };
        };
      };
    };
  };
  /**
   * Delete a custom field
   * @description Permanently delete a product's custom field.
   */
  "/products/{product_id}/custom_fields/{name}.delete": {
    parameters: {
      path: {
        product_id: string;
        name: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            message: string;
          };
        };
      };
    };
  };
  /**
   * Get current user data
   * @description Retrieve the user's data.
   */
  "/user.get": {
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            user: {
              bio: string;
              facebook_profile?: unknown;
              name: string;
              twitter_handle?: unknown;
              user_id: string;
              email: string;
              url: string;
            };
          };
        };
      };
    };
  };
  /**
   * List resource subscriptions
   * @description Show all active subscriptions of user for the input resource.
   */
  "/resource_subscriptions.get": {
    parameters: {
      query: {
        resource_name: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            resource_subscriptions: {
                id: string;
                resource_name: string;
                post_url: string;
              }[];
          };
        };
      };
    };
  };
  /**
   * Subscribe to a resource
   * @description Subscribe to a resource. Currently there are 5 supported resource names - "sale", "refund", "dispute", "dispute_won", and "cancellation". sale - When subscribed to this resource, you will be notified of the user's sales with an HTTP POST to your post_url. The format of the POST is described on the Gumroad Ping page.refund - When subscribed to this resource, you will be notified of refunds to the user's sales with an HTTP POST to your post_url. The format of the POST is same as described on the Gumroad Ping page.dispute - When subscribed to this resource, you will be notified of the disputes raised against user's sales with an HTTP POST to your post_url. The format of the POST is described on the Gumroad Ping page.dispute_won - When subscribed to this resource, you will be notified of the sale disputes won by the user with an HTTP POST to your post_url. The format of the POST is described on the Gumroad Ping page.cancellation - When subscribed to this resource, you will be notified of cancellations of the user's subscribers with an HTTP POST to your post_url.In each POST request, Gumroad sends these parameters:
   * subscription_id: id of the subscription
   * product_id: id of the product
   * product_name: name of the product
   * user_id: user id of the subscriber
   * user_email: email address of the subscriber
   * purchase_ids: array of charge ids belonging to this subscription
   * created_at: timestamp when subscription was created
   * charge_occurrence_count: number of charges made for this subscription
   * recurrence: subscription duration - monthly/quarterly/biannually/yearly
   * cancelled: true if subscription has been cancelled, otherwise false
   * cancelled_at: timestamp at which subscription was cancelled
   * cancelled_by_admin: true if subscription was been cancelled by admin, otherwise not present
   * cancelled_by_buyer: true if subscription was been cancelled by buyer, otherwise not present
   * cancelled_by_seller: true if subscription was been cancelled by seller, otherwise not present
   * cancelled_due_to_payment_failures: true if subscription was been cancelled automatically because of payment failure, otherwise not present
   */
  "/resource_subscriptions.put": {
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            resource_subscription: {
              id: string;
              resource_name: string;
              post_url: string;
            };
          };
        };
      };
    };
  };
  /**
   * Unsubscribe from resource
   * @description Unsubscribe from a resource.
   */
  "/resource_subscriptions/{resource_subscription_id}.delete": {
    parameters: {
      path: {
        resource_subscription_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            message: string;
          };
        };
      };
    };
  };
  /**
   * List sales
   * @description Retrieves all of the successful sales by the authenticated user.
   */
  "/sales.get": {
    parameters: {
      query: {
        after?: string;
        before?: string;
        email?: string;
        page: number;
        product_id?: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            next_page_url: string;
            sales: {
                id: string;
                email: string;
                seller_id: string;
                timestamp: string;
                created_at: string;
                product_name: string;
                price: number;
                gumroad_fee: number;
                subscription_duration: string;
                formatted_display_price: string;
                formatted_total_price: string;
                product_id: string;
                purchase_email: string;
                full_name: string;
                paid: boolean;
                variants: string;
                variants_and_quantity: string;
                has_custom_fields: boolean;
                custom_fields?: {
                  "Twitter handle": string;
                };
                order_id: number;
                is_product_physical: boolean;
                purchaser_id: string;
                is_recurring_billing: boolean;
                is_following: boolean;
                subscription_id: string;
                cancelled: boolean;
                ended: boolean;
                referrer: string;
              }[];
          };
        };
      };
    };
  };
  /**
   * Get a sale
   * @description Retrieves the details of a sale by this user.
   */
  "/sales/{id}.get": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            sale: {
              id: string;
              email: string;
              seller_id: string;
              timestamp: string;
              created_at: string;
              product_name: string;
              price: number;
              gumroad_fee: number;
              subscription_duration: string;
              formatted_display_price: string;
              formatted_total_price: string;
              product_id: string;
              purchase_email: string;
              full_name: string;
              paid: boolean;
              variants: string;
              variants_and_quantity: string;
              has_custom_fields: boolean;
              custom_fields: {
                "Twitter handle": string;
              };
              order_id: number;
              is_product_physical: boolean;
              purchaser_id: string;
              is_recurring_billing: boolean;
              is_following: boolean;
              subscription_id: string;
              cancelled: boolean;
              ended: boolean;
              referrer: string;
              quantity: number;
            };
          };
        };
      };
    };
  };
  /**
   * Mark sale as shipped
   * @description Marks a sale as shipped.
   */
  "/sales/{id}/mark_as_shipped.put": {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          tracking_url?: string;
        };
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            sale: {
              id: string;
              email: string;
              timestamp: string;
              created_at: string;
              product_name: string;
              price: number;
              subscription_duration: string;
              formatted_display_price: string;
              formatted_total_price: string;
              product_id: string;
              purchase_email: string;
              full_name: string;
              paid: boolean;
              variants: string;
              variants_and_quantity: string;
              has_custom_fields: boolean;
              custom_fields: {
                "Twitter handle": string;
              };
              order_id: number;
              is_product_physical: boolean;
              purchaser_id: string;
              is_recurring_billing: boolean;
              is_following: boolean;
              subscription_id: string;
              cancelled: boolean;
              ended: boolean;
              referrer: string;
              shipped: boolean;
              tracking_url: string;
              quantity: number;
            };
          };
        };
      };
    };
  };
  /**
   * Refund a sale
   * @description Refunds a sale.
   */
  "/sales/{id}/refund.put": {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          amount_cents?: number;
        };
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            sale: {
              id: string;
              email: string;
              timestamp: string;
              daystamp: string;
              created_at: string;
              product_name: string;
              product_has_variants: boolean;
              price: number;
              formatted_display_price: string;
              formatted_total_price: string;
              currency_symbol: string;
              amount_refundable_in_currency: string;
              product_id: string;
              product_permalink: string;
              refunded: boolean;
              partially_refunded: boolean;
              chargedback: boolean;
              purchase_email: string;
              full_name: string;
              paid: boolean;
              has_variants: boolean;
              variants_and_quantity: string;
              has_custom_fields: boolean;
              custom_fields: {
                "Twitter handle": string;
              };
              order_id: number;
              is_product_physical: boolean;
              purchaser_id: string;
              is_recurring_billing: boolean;
              can_contact: boolean;
              is_following: boolean;
              cancelled: boolean;
              ended: boolean;
              is_additional_contribution: boolean;
              discover_fee_charged: boolean;
              is_gift_sender_purchase: boolean;
              is_gift_receiver_purchase: boolean;
              referrer: string;
              card: {
                visual: string;
                type: string;
                bin?: unknown;
                expiry_month: number;
                expiry_year: number;
              };
              product_rating?: unknown;
              reviews_count: number;
              average_rating: number;
              quantity: number;
            };
          };
        };
      };
    };
  };
  /**
   * List product subscribers
   * @description Retrieves all of the active subscribers for one of the authenticated user's products.
   */
  "/products/{product_id}/subscribers.get": {
    parameters: {
      query?: {
        email?: string;
      };
      path: {
        product_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            subscribers: {
                id: string;
                product_id: string;
                product_name: string;
                user_id: string;
                user_email: string;
                purchase_ids?: unknown[];
                created_at: string;
                cancelled_at?: unknown;
                user_requested_cancellation_at?: unknown;
                charge_occurrence_count?: unknown;
                recurrence: string;
                ended_at?: unknown;
              }[];
          };
        };
      };
    };
  };
  /**
   * Get a product subscriber
   * @description Retrieves the details of a subscriber to this user's product.
   */
  "/subscribers/{id}.get": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            subscribers: {
              id: string;
              product_id: string;
              product_name: string;
              user_id: string;
              user_email: string;
              purchase_ids: unknown[];
              created_at: string;
              cancelled_at?: unknown;
              user_requested_cancellation_at?: unknown;
              charge_occurrence_count?: unknown;
              recurrence: string;
              ended_at?: unknown;
            };
          };
        };
      };
    };
  };
  /**
   * Verify a license
   * @description Verify a license
   */
  "/licenses/verify.post": {
    requestBody?: {
      content: {
        "application/json": {
          product_permalink: string;
          license_key: string;
          /** @default true */
          increment_uses_count?: boolean;
        };
      };
    };
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            uses: number;
            purchase: {
              id: string;
              seller_id: string;
              purchaser_id: string;
              gumroad_fee: string;
              product_name: string;
              created_at: string;
              full_name: string;
              variants: string;
              refunded: boolean;
              chargebacked: boolean;
              subscription_cancelled_at?: unknown;
              subscription_failed_at?: unknown;
              custom_fields: unknown[];
              email: string;
            };
          };
        };
      };
    };
  };
  /**
   * Enable a license
   * @description Enable a license
   */
  "/licenses/enable.put": {
    requestBody: components["requestBodies"]["Body3"];
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            uses: number;
            purchase: {
              id: string;
              seller_id: string;
              purchaser_id: string;
              gumroad_fee: string;
              product_name: string;
              created_at: string;
              full_name: string;
              variants: string;
              refunded: boolean;
              chargebacked: boolean;
              subscription_cancelled_at?: unknown;
              subscription_failed_at?: unknown;
              custom_fields: unknown[];
              email: string;
            };
          };
        };
      };
    };
  };
  /**
   * Disable a license
   * @description Disable a license
   */
  "/licenses/disable.put": {
    requestBody: components["requestBodies"]["Body3"];
    responses: {
      200: {
        content: {
          "*/*": {
            success: boolean;
            uses: number;
            purchase: {
              id: string;
              seller_id: string;
              purchaser_id: string;
              gumroad_fee: string;
              product_name: string;
              created_at: string;
              full_name: string;
              variants: string;
              refunded: boolean;
              chargebacked: boolean;
              subscription_cancelled_at?: unknown;
              subscription_failed_at?: unknown;
              custom_fields: unknown[];
              email: string;
            };
          };
        };
      };
    };
  };
}
